spring.application.name=ai-interview-coach

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_interview_coach
spring.datasource.username=postgres
spring.datasource.password=Hardoi@5

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
