
spring.application.name=ai-interview-coach

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_interview_coach
spring.datasource.username=postgres
spring.datasource.password=Hardoi@5

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=MySecretKeyForAIInterviewCoachProject2026SpringBootJWT

# Spring AI + OpenRouter

spring.ai.openai.api-key=${OPENROUTER_API_KEY}

spring.ai.openai.chat.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=openai/gpt-4.1-mini
spring.ai.openai.chat.options.max-tokens=1000

# Debug Logging

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=TRACE